<?php

use Illuminate\Database\Seeder;
use App\Ingredient;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */


    public function run()
    {
        DB::table('ingredients')->delete();

        $fruit = 'constants.fruit_category_id';
        $veg = 'constants.veg_category_id';
        $dairy = 'constants.dairy_category_id';
        $herb = 'constants.herb_category_id';
        $spice = 'constants.spice_category_id';
        $meat = 'constants.meat_category_id';

        $ingredients = array(
            array('name' => 'romaine lettuce', 'ingredient_category_id'=> Config::get($veg)),
            array('name' => 'black olives', 'ingredient_category_id'=> Config::get($fruit)),
            array('name' => 'grape tomatoes', 'ingredient_category_id'=> Config::get($fruit)),
            array('name' => 'garlic', 'ingredient_category_id' => Config::get($spice)),
//            'pepper',
//            'purple onion',
//            'salt',
//            'beans',
//            'feta cheese',
//            'apple',
//            'apricot',
//            'avocado',
//            'banana',
//            'bilberry',
//            'blackberry',
//            'blackcurrant',
//            'blueberry',
//            'boysenberry',
//            'currant',
//            'cherry',
//            'chico fruit',
//            'coconut',
//            'cranberry',
//            'cucumber',
//            'sugar apple',
//            'damson',
//            'date',
//            'dragonfruit',
//            'durian',
//            'elderberry',
//            'feijoa',
//            'fig',
//            'goji berry',
//            'gooseberry',
//            'grape',
//            'raisin',
//            'grapefruit',
//            'guava',
//            'honeyberry',
//            'huckleberry',
//            'jabuticaba',
//            'jackfruit',
//            'jambul',
//            'jujube',
//            'juniper berry',
//            'kiwifruit',
//            'kumquat',
//            'lemon',
//            'lime',
//            'loquat',
//            'longan',
//            'lychee',
//            'mango',
//            'marionberry',
//            'melon',
//            'cantaloupe',
//            'honeydew',
//            'watermelon',
//            'miracle fruit',
//            'mulberry',
//            'nectarine',
//            'nance',
//            'olive',
//            'orange',
//            'blood orange',
//            'clementine',
//            'mandarine',
//            'tangerine',
//            'papaya',
//            'passionfruit',
//            'peach',
//            'pear',
//            'persimmon',
//            'physalis',
//            'plantain',
//            'plum',
//            'prune (dried plum)',
//            'pineapple',
//            'plumcot (or Pluot)',
//            'pomegranate',
//            'pomelo',
//            'purple mangosteen',
//            'quince',
//            'raspberry',
//            'salmonberry',
//            'rambutan',
//            'redcurrant',
//            'salal berry',
//            'salak',
//            'satsuma',
//            'soursop',
//            'star fruit',
//            'solanum quitoense',
//            'strawberry',
//            'tamarillo',
//            'tamarind',
//            'ugli fruit',
//            'yuzu',
//            //veg
//            'Artichoke',
//            'Arugula',
//            'Asparagus',
//            'Aubergine',
//            'Eggplant',
//            'Amaranth',
//            'Legumes',
//            'Alfalfa sprouts',
//            'Azuki beans',
//            'Bean sprouts',
//            'Black beans',
//            'Black-eyed peas',
//            'Borlotti bean',
//            'Broad beans',
//            'Chickpeas',
//            'Garbanzos',
//            'Green beans',
//            'Kidney beans',
//            'Lentils',
//            'Lima beans',
//            'Butter bean',
//            'Mung beans',
//            'Navy beans',
//            'Pinto beans',
//            'Runner beans',
//            'Split peas',
//            'Soy beans',
//            'Peas',
//            'Mangetout',
//            'Snap peas',
//            'Beet greens',
//            'Bok choy',
//            'Broccoflower',
//            'Broccoli',
//            'Brussels sprouts',
//            'Cabbage',
//            'Calabrese',
//            'Carrots',
//            'Cauliflower',
//            'Celery',
//            'Chard',
//            'Collard greens',
//            'Corn salad',
//            'Endive',
//            'Fiddleheads',
//            'Frisee',
//            'Fennel',
//            //Herbs
//            'Anise',
//            'Basil',
//            'Caraway',
//            'Cilantro',
//            'Coriander',
//            'Chamomile',
//            'Dill',
//            'Fennel',
//            'Lavender',
//            'Lemon Grass',
//            'Marjoram',
//            'Oregano',
//            'Parsley',
//            'Rosemary',
//            'Sage',
//            'Thyme',
//            'Kale',
//            'Kohlrabi',
//            'Lettuce Lactuca sativa',
//            'Maize',
//            'Corn',
//            'Sweetcorn',
//            'Mushrooms',
//            'Mustard greens',
//            'Nettles',
//            'Okra',
//            //Onion
//            'Chives',
//            'Garlic',
//            'Leek Allium porrum',
//            'Onion',
//            'Shallot',
//            'Spring onion',
//            'Green onion',
//            'Scallion',
//            'Parsley',
//            'Peppers',
//            'Green pepper',
//            'Red pepper',
//            'Chili pepper',
//            'Capsicum',
//            'Jalapeño',
//            'Habanero',
//            'Paprika',
//            'Tabasco pepper',
//            'Cayenne pepper',
//            'Radicchio',
//            'Rhubarb',
//            'Root vegetables',
//            'Beetroot',
//            'beet',
//            'Carrot',
//            'Celeriac',
//            'Daikon',
//            'Ginger',
//            'Parsnip',
//            'Rutabaga',
//            'Turnip',
//            'Radish',
//            'Swede',
//            'Rutabaga',
//            'Turnip',
//            'Wasabi',
//            'Horseradish',
//            'White radish',
//            'Salsify',
//            'Skirret',
//            'Spinach',
//            'Topinambur',
//            'Squashes',
//            'Acorn squash',
//            'Butternut squash',
//            'Banana squash',
//            'Courgette',
//            'Cucumber',
//            'Delicata',
//            'Gem squash',
//            'Hubbard squash',
//            'Marrow',
//            'Squash',
//            'Cucurbita maxima',
//            'Patty pans',
//            'Pumpkin',
//            'Spaghetti squash',
//            'Tat soi',
//            'Tomato',
//            'Tubers',
//            'Jicama',
//            'Jerusalem artichoke',
//            'Potato',
//            'Quandong',
//            'Sunchokes',
//            'Sweet potato',
//            'Taro',
//            'Yam',
//            'Turnip greens',
//            'Water chestnut',
//            'Watercress',
//            'Zucchini'
        );

        foreach ($ingredients as $ingredient) {

            Ingredient::create(array(
                'name' => $ingredient['name'],
                'ingredient_category_id' => $ingredient['ingredient_category_id'])
            );

            // DB::table('industries')->insert($industry);
        }

//        for($i = 0; $i < count($ingredients); $i++){
//            Ingredient::create(array(
//               'name' => $ingredients[$i]
//            ));
//        }
    }
}
